// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/kennyhong/scp.jce'
// **********************************************************************

package me.longerian.abc.hex;

public final class TransDataMessageHolder
{
    public TransDataMessageHolder()
    {
    }
    public TransDataMessageHolder(TransDataMessage value)
    {
        this.value = value;
    }

    public TransDataMessage value;
}
