// automatically generated by the FlatBuffers compiler, do not modify

package me.longerian.fbs;

public final class FriendshipStatus {
  private FriendshipStatus() { }
  public static final int Friend = 1;
  public static final int NotFriend = 2;

  public static final String[] names = { "Friend", "NotFriend", };

  public static String name(int e) { return names[e - Friend]; }
}

