// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/kennyhong/scp.jce'
// **********************************************************************

package me.longerian.abc.hex;

public final class TransMessageType implements java.io.Serializable
{
    private static TransMessageType[] __values = new TransMessageType[6];
    private int __value;
    private String __T = new String();

    public static final int _TRANS_MESSAGE_TYPE_DATA = 0;
    public static final TransMessageType TRANS_MESSAGE_TYPE_DATA = new TransMessageType(0,_TRANS_MESSAGE_TYPE_DATA,"TRANS_MESSAGE_TYPE_DATA");
    public static final int _TRANS_MESSAGE_TYPE_CONNECT = 1;
    public static final TransMessageType TRANS_MESSAGE_TYPE_CONNECT = new TransMessageType(1,_TRANS_MESSAGE_TYPE_CONNECT,"TRANS_MESSAGE_TYPE_CONNECT");
    public static final int _TRANS_MESSAGE_TYPE_CLOSE = 2;
    public static final TransMessageType TRANS_MESSAGE_TYPE_CLOSE = new TransMessageType(2,_TRANS_MESSAGE_TYPE_CLOSE,"TRANS_MESSAGE_TYPE_CLOSE");
    public static final int _TRANS_MESSAGE_TYPE_PACKET_LOST = 3;
    public static final TransMessageType TRANS_MESSAGE_TYPE_PACKET_LOST = new TransMessageType(3,_TRANS_MESSAGE_TYPE_PACKET_LOST,"TRANS_MESSAGE_TYPE_PACKET_LOST");
    public static final int _TRANS_MESSAGE_TYPE_ACK = 4;
    public static final TransMessageType TRANS_MESSAGE_TYPE_ACK = new TransMessageType(4,_TRANS_MESSAGE_TYPE_ACK,"TRANS_MESSAGE_TYPE_ACK");
    public static final int _TRANS_MESSAGE_TYPE_STOP_RESEND = 5;
    public static final TransMessageType TRANS_MESSAGE_TYPE_STOP_RESEND = new TransMessageType(5,_TRANS_MESSAGE_TYPE_STOP_RESEND,"TRANS_MESSAGE_TYPE_STOP_RESEND");

    public static TransMessageType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static TransMessageType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private TransMessageType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
